plotly:
  theme: plotly_white
  renderer: vscode+pdf+png+jpeg
  colors:
    blue: '#1D69E0'
    red: '#FA4549'
  transparency: 0.65
  histogram:
    nbins: 30

purchase-database:
  columns:
    produto: product_name
    categoria_produto: product_category
    data_compra: purchase_date
    valor_compra: purchase_value
    pais: country
    score_1: score_1
    score_2: score_2
    score_3: score_3
    score_4: score_4
    score_5: score_5
    score_6: score_6
    score_7: score_7
    score_8: score_8
    score_9: score_9
    score_10: score_10
    entrega_doc_1: document_delivery_1
    entrega_doc_2: document_delivery_2
    entrega_doc_3: document_delivery_3
    score_fraude_modelo: fraud_score_model
    fraude: fraud
  quantiles:
    min: 0.005
    max: 0.995

models:
  split:
    train: 0.7
    calib: 0.1
    test: 0.2
  features:
    - purchase_value
    - country
    - score_1
    - score_2
    - score_3
    - score_4
    - score_5
    - score_6
    - score_7
    - score_8
    - score_9
    - score_10
    - document_delivery_1
    - document_delivery_2
    - document_delivery_3
  target:
    - fraud